# https://github.com/jupyterlab/maintainer-tools/blob/main/.github/actions/update-snapshots/action.yml
name: Update VRT base

inputs:
  github_token:
    description: The token used to make requests to the GitHub API. It's NOT used to make commits and should not be changed.
    required: false
    default: ${{ github.token }}
  branch:
    required: true
    description: Specify which branch should be used

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      shell: bash -l {0}
      run: yarn
    - name: Install Playwright Browsers
      shell: bash -l {0}
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      shell: bash -l {0}
      run: yarn test:vrt --update-snapshots
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Commit new snapshots
      shell: bash -l {0}
      working-directory: tests/vrt
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git pull --no-tags
        git add .
        git commit -m "Update Snapshots"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Push new snapshots
      shell: bash -l {0}
      run: |
        git config push.default upstream
        git push
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
