name: Check message
on:
    issue_comment:
        types: [created]

jobs:
    update-screenshots:
        runs-on: ubuntu-latest
        steps:
            - uses: khan/pull-request-comment-trigger@v1.1.0
              id: check
              with:
                  trigger: "@update-snapshots"
                  reaction: rocket
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            # https://github.community/t/path-to-action-in-the-same-repository-as-workflow/16952/2
            - name: Checkout
              uses: actions/checkout@v4
            - name: Checkout Pull Request
              run: gh pr checkout ${{ github.event.issue.number }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Start VRT Update
              if: steps.check.outputs.triggered == 'true'
              uses: ./.github/actions/update-vrt-base
              with:
                  # Recommended: pass the GitHub token lets this action correctly
                  # determine the unique run id necessary to re-run the checks
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.ref }}
